In [1]:
# Importar librerias
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/drive/MyDrive/ReconocimientoPatrones/train.csv')
data.head()

Mounted at /content/drive


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
# Funcion para dividir age en 4 categorias
def age_class(x):
    if np.double(x)>= 0 and np.double(x) < 18:
        x = 1.0;
    elif np.double(x) >=18 and np.double(x)< 25:
        x = 2.0;
    elif np.double(x) >=25 and np.double(x) < 35:
        x = 3.0;
    else:
        x = 4.0;
    return x;

In [3]:
# Se aplica la funcion age_class para que ahora las edades esten agrpupadas en
# 4 categorias
data.Age = data['Age'].apply(age_class)

In [4]:
data['Age']

0      2.0
1      4.0
2      3.0
3      4.0
4      4.0
      ... 
886    3.0
887    2.0
888    4.0
889    3.0
890    3.0
Name: Age, Length: 891, dtype: float64

In [5]:
X = data[['Pclass', 'Sex','Age','SibSp','Parch']].values
X

array([[3, 'male', 2.0, 1, 0],
       [1, 'female', 4.0, 1, 0],
       [3, 'female', 3.0, 0, 0],
       ...,
       [3, 'female', 4.0, 1, 2],
       [1, 'male', 3.0, 0, 0],
       [3, 'male', 3.0, 0, 0]], dtype=object)

In [6]:
y = data['Survived'].values
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [7]:
y_train = y[:600] # Training
y_val = y[600:] # Testing

X_train = X[:600] # Training
X_val = X[600:] # Testing

In [8]:
X_train

array([[3, 'male', 2.0, 1, 0],
       [1, 'female', 4.0, 1, 0],
       [3, 'female', 3.0, 0, 0],
       ...,
       [3, 'male', 4.0, 0, 0],
       [3, 'male', 4.0, 0, 0],
       [1, 'male', 4.0, 1, 0]], dtype=object)

In [9]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [10]:
X_val

array([[2, 'female', 2.0, 2, 1],
       [3, 'male', 4.0, 0, 0],
       [1, 'male', 4.0, 0, 0],
       ...,
       [3, 'female', 4.0, 1, 2],
       [1, 'male', 3.0, 0, 0],
       [3, 'male', 3.0, 0, 0]], dtype=object)

In [11]:
y_val

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0])

In [12]:
count = {} # Diccionario para almacenar numero de muertos y sobrevivientes
datos = [] # Lista para almacenar todos los datos del training set

In [13]:
for i in range(len(X_train)): # itera en los 600 elementos de entrenamiento
  # si es una clasificacion diferente ej. muerto se agrega al diccionario
  # y se toma como un valor de 1, ej. muerto: 1
  if not y_train[i] in count.keys():
    count[y_train[i]] = 1            
  # si es una clasificacion ya existente se le suma 1 al valor
  # ej. muerto: 2
  else:
    count[y_train[i]] += 1
  
  datos.append([X_train[i], y_train[i]])

# Muestra el total de elementos por categoria
print('Count: ',count) # En este caso numero de muertos y sobrevivientes
# Muestra el total de los datos
print('Datos: ', datos)

Count:  {0: 364, 1: 236}
Datos:  [[array([3, 'male', 2.0, 1, 0], dtype=object), 0], [array([1, 'female', 4.0, 1, 0], dtype=object), 1], [array([3, 'female', 3.0, 0, 0], dtype=object), 1], [array([1, 'female', 4.0, 1, 0], dtype=object), 1], [array([3, 'male', 4.0, 0, 0], dtype=object), 0], [array([3, 'male', 4.0, 0, 0], dtype=object), 0], [array([1, 'male', 4.0, 0, 0], dtype=object), 0], [array([3, 'male', 1.0, 3, 1], dtype=object), 0], [array([3, 'female', 3.0, 0, 2], dtype=object), 1], [array([2, 'female', 1.0, 1, 0], dtype=object), 1], [array([3, 'female', 1.0, 1, 1], dtype=object), 1], [array([1, 'female', 4.0, 0, 0], dtype=object), 1], [array([3, 'male', 2.0, 0, 0], dtype=object), 0], [array([3, 'male', 4.0, 1, 5], dtype=object), 0], [array([3, 'female', 1.0, 0, 0], dtype=object), 0], [array([2, 'female', 4.0, 0, 0], dtype=object), 1], [array([3, 'male', 1.0, 4, 1], dtype=object), 0], [array([2, 'male', 4.0, 0, 0], dtype=object), 1], [array([3, 'female', 3.0, 1, 0], dtype=object), 

In [14]:
# Ejemplo del set de Testeo
entry = X_val[186]
entry

array([3, 'female', 2.0, 0, 0], dtype=object)

In [15]:
# Iterando en la lista datos se busca aquellos que coincidan con la columna 1
# y que esten clasificados como vivos (1)
# La columna 1 es de Genero y nuestra muestra es Mujer por lo que se imprime
# el numero de mujeres vivas de nuestro training set
cases = [x for x in datos if x[0][1] == entry[1] and x[1] == 1]
len(cases)

167

In [16]:
# Este mismo proceso se realiza para cada columna (Pclass, age, etc)
# y para cada clasificacion (vivos y muertos)

result = 0 # resultado de la prediccion(vivo:1, muerto:0)
max_prob = -1 # probabilidad a comparar para determinar cual es mayor

for j in count.keys(): # itera en el numero de clasificaciones (0,1 en este caso)
  # probabilidad de cada categoria (0,1)
  p_total = count[j]/len(X_train) # total de vivos o muertos/total de pasajeros(600)
  for i in range(len(X_train[0])): # itera en las 5 columnas
    cases = [x for x in datos if x[0][i] == entry[i] and x[1] == j]
    # Al numero de elementos por categoria se divide entre la probabilidad
    # de vivir o morir segun sea el caso
    n = len(cases) / np.sum(y_train == j) # total de muertos o vivos segun sea el caso
    # Se multiplica cada elemento por categoria de la muestra
    # Es decir: pclass*sex*age...
    # Y se multiplica por p_total
    p_total *= n
                
  # Decide si se sobrevive o no si p_total es mayor a la max_prob
  # p_total se almacena en max_prob para realizar la comparacion entre 
  # probabilidad de morir y probabilidad de vivir
  if p_total > max_prob:
    max_prob = p_total
    result = j # j ocupa valores de 0 y 1

In [17]:
# Todo lo anterior se junta en la clase Classifier
class Classifier:   
    def __init__(self, X_train, y_train, X_val, y_val):
        self.X1, self.y1, self.X2, self.y2 = X_train, y_train, X_val, y_val

        self.count = {}

        self.datos = []
         
        for i in range(len(self.X1)):      
            if not self.y1[i] in self.count.keys():
                self.count[self.y1[i]] = 1
            else:
                self.count[self.y1[i]] += 1

            self.datos.append([self.X1[i], self.y1[i]])
            
    def classify(self, entry):

        result = None 
        max_prob = -1 

        for j in self.count.keys():

            p_total = self.count[j]/len(self.X1)

            for i in range(len(self.X1[0])):
                cases = [x for x in self.datos if x[0][i] == entry[i] and x[1] == j]
                n = len(cases)/ np.sum(y_train == j)
                p_total *= n
                
            if p_total > max_prob:
                max_prob = p_total
                result = j

        return result

    # Funcion para el display de stats del classifier
    def accuracy_score(self):
      accuracy = 0
      error = 0
      index = -1
      for i in range(len(self.y2)):
        index += 1
        predict = bayes.classify(self.X2[index])
        if self.y2[i] == predict:
            accuracy += 1
        else:
            error += 1

      accuracy_score = round(accuracy/self.y2.shape[0], 6)
      print('number of successes:', accuracy)
      print('number of failures:', error)
      print('accuracy score: %f'%accuracy_score)

In [18]:
bayes = Classifier(X_train, y_train, X_val, y_val)
bayes.accuracy_score()

number of successes: 229
number of failures: 62
accuracy score: 0.786942
